### ISSUE TITLE
A question about ’smootheem‘

### ISSUE THREAD

**Issue by Annmun** [alex-goranov/TEnvR#1]
Why are the parameters in Slide 42 and Slide 60 so different?
‘Slide 60: DS_Smooth=smootheem(DS_undiluted,[15 300],[15 15],[350 20],[10 10],[0 0 0 0],[],3382,'pause');’
‘Slide 42: DS_Smooth=smootheem(DS_undiluted,[10 10],[10 10],[20 20],[10 10],[0 0 0 0],[],3382,'pause');’
How to get 300?

**Comment by alex-goranov** [comment]
Parameters are different, because these are two different datasets of fluorescence data acquired on two different instruments. Slides 35-48 show workup of EEMs acquired on an Aqualog while Slides 53-63 show workup of EEMs acquired on a Shimadzu spectrofluorimeter. Thus, each different set of EEM spectra has different levels of scattering, noise, and other artifacts that require different parameters in the smootheem function. 

The value of 300 is basicaly how much it was needed to delete the data from the scattering band to the boundaries of the EEM. I suggest playing around and trying differnent values in the first five boxes (i.e., [15 300],[15 15],[350 20],[10 10]) to see how this function operates. You can also review its supporting information within the drEEM toolbox (or here: https://dreem.openfluor.org/tutorials/smoothing/)

**Comment by Annmun** [comment]
> Parameters are different, because these are two different datasets of fluorescence data acquired on two different instruments. Slides 35-48 show workup of EEMs acquired on an Aqualog while Slides 53-63 show workup of EEMs acquired on a Shimadzu spectrofluorimeter. Thus, each different set of EEM spectra has different levels of scattering, noise, and other artifacts that require different parameters in the smootheem function.
> 
> The value of 300 is basicaly how much it was needed to delete the data from the scattering band to the boundaries of the EEM. I suggest playing around and trying differnent values in the first five boxes (i.e., [15 300],[15 15],[350 20],[10 10]) to see how this function operates. You can also review its supporting information within the drEEM toolbox (or here: https://dreem.openfluor.org/tutorials/smoothing/)

**Comment by Annmun** [comment]
Thanks for your reply. I have read the tutorials as the follow picture.
![微信截图_20240507093830](https://github.com/alex-goranov/TEnvR/assets/53742054/b852a7e5-9f62-4932-a46d-468e2011ecbd)
I think 11nm, 9nm, 14nm and 16nm are obtained by subtracting the wavelengths. So I'm wondering how to get 300?

**Comment by alex-goranov** [comment]
300 is an arbitrary number, it is not calculated. It is basically sufficient enough to delete all data up to the boundary of the EEM. You can play around and see what number is best, I think I had tried 250 and didn't work to completely erase all data, so 300 works. To see what I am talking about, I suggest going using the function from  Slide 60: DS_Smooth=smootheem(DS_undiluted,[15 300],[15 15],[350 20],[10 10],[0 0 0 0],[],3382,'pause'); and trying 100, 150, 200, 250, 300 in the first [] to see what ends up happening. I really wanted to just trim than entire region of no data.

**Comment by Annmun** [comment]
> 300 is an arbitrary number, it is not calculated. It is basically sufficient enough to delete all data up to the boundary of the EEM. You can play around and see what number is best, I think I had tried 250 and didn't work to completely erase all data, so 300 works. To see what I am talking about, I suggest going using the function from Slide 60: DS_Smooth=smootheem(DS_undiluted,[15 300],[15 15],[350 20],[10 10],[0 0 0 0],[],3382,'pause'); and trying 100, 150, 200, 250, 300 in the first [] to see what ends up happening. I really wanted to just trim than entire region of no data.

Thank you for your reply, I have learned how to get the right EEM.
